env: 'prod'
debug: false
webpack:
  main_entry_name: 'app'
  assets_manifest: '/assets/assets.json'
route:
  names:
    home: 'route.home'
    about: 'route.about'
    contact: 'route.contact'
    project: 'route.project'
data:
  file_ext: '.tx'
  filenames:
    about: 'about'
    contact: 'contact'
    project: 'data'
