env: 'prod'
debug: false
route:
  names:
    home: 'route.home'
    about: 'route.about'
    contact: 'route.contact'
    project: 'route.project'
data:
  file_ext: '.tx'
  filenames:
    about: 'about'
    contact: 'contact'
    project: 'data'
